id: ebc2548c-a4c3-402a-b617-389da41292d7
name: Mariadb-sdk-plugin
language: PYTHON27
hostTypes:
- UNIX
pluginType: STAGED
entryPoint: plugin_runner:plugin
srcDir: src
rootSquashEnabled: false
schemaFile: schema.json
buildNumber: 0.1.1

